# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in fiber_gauge.gemspec
gemspec

group :test do
  gem "rake"
  gem "simplecov", require: false
  gem "simplecov-json", require: false
end
