# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new do |t|
  t.libs << "test"
  t.pattern = "test/**/*_test.rb"
end

task default: :test

namespace :db do
  desc "Run database migrations"
  task :migrate do
    require_relative "config/environment"
    Sequel::Migrator.run(DB, File.join(__dir__, "db", "migrations"))
    puts "Migrations complete."
  end
end
