# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in fiber_gauge.gemspec
gemspec

group :test do
  gem "simplecov", require: false
end

gem "rake", "~> 13.3", group: :test
gem "simplecov-json", "~> 0.2.3", group: :test
