name: CraftOS CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.4", "4.0"]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run StandardRB
        run: bundle exec standardrb

      - name: Run all gem tests
        run: bundle exec rake test:all

      - name: Ensure minimum coverage
        uses: joshmfrankel/simplecov-check-action@main
        with:
          minimum_suite_coverage: 95
          minimum_file_coverage: 90
          github_token: ${{ secrets.GITHUB_TOKEN }}
